# Generated by Django 4.0.8 on 2024-09-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
    ]
