# Generated by Django 4.0.8 on 2024-09-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_remove_application_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='class_applying',
            field=models.CharField(choices=[('OSUN', 'OSUN'), ('OYO', 'OYO')], max_length=10),
        ),
    ]
