# Generated by Django 4.0.8 on 2024-09-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_alter_application_class_applying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='class_applying',
            field=models.CharField(choices=[('JSS 1', 'JSS 1'), ('JSS 2', 'JSS 2'), ('JSS 3', 'JSS 3'), ('SSS 1', 'SSS 1'), ('SSS 2', 'SSS 2'), ('SSS 3', 'SSS 3')], max_length=10),
        ),
    ]
