# Generated by Django 4.0.8 on 2024-09-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_alter_application_class_applying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='state_of_origin',
            field=models.CharField(choices=[('OSUN', 'OSUN'), ('OYO', 'OYO')], max_length=100),
        ),
    ]
