# Generated by Django 4.0.8 on 2024-09-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_alter_application_state_of_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admission_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
