# Generated by Django 4.0.8 on 2024-09-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_application_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='department',
            field=models.CharField(choices=[('SCIENCE', 'SCIENCE'), ('ART', 'ART'), ('SOCIAL_SCIENCE', 'SOCIAL_SCIENCE')], default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
