# Generated by Django 4.0.8 on 2024-09-21 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_application_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='water_fee',
        ),
    ]
