# Generated by Django 4.0.8 on 2024-09-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_remove_payment_water_fee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='School_Fee_Payment',
        ),
    ]
