# Generated by Django 5.1.1 on 2024-09-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0009_rename_payment_school_fee_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_session", models.CharField(max_length=100)),
            ],
        ),
    ]
