# Generated by Django 5.1.1 on 2024-09-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0010_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="date_admission_approved",
            field=models.DateField(blank=True, null=True),
        ),
    ]
