# Generated by Django 5.1.1 on 2024-09-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0012_course_courseregistration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseRegistration",
        ),
    ]
