# Generated by Django 5.1.1 on 2024-09-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0015_course_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="school_fee_payment",
            name="date_paid",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="school_fee_payment",
            name="transaction_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
