# Generated by Django 5.1.1 on 2024-09-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0016_school_fee_payment_date_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="class_applying",
            field=models.CharField(
                choices=[
                    ("CREACH", "CREACH"),
                    ("KG1", "KG1"),
                    ("KG2", "KG2"),
                    ("NURSERY1", "NURSERY1"),
                    ("NURSERY2", "NURSERY3"),
                    ("NURSERY3", "NURSERY3"),
                    ("PRIMARY1", "PRIMARY1"),
                    ("PRIMARY2", "PRIMARY2"),
                    ("PRIMARY2", "PRIMARY2"),
                    ("PRIMARY3", "PRIMARY3"),
                    ("PRIMARY4", "PRIMARY4"),
                    ("PRIMARY5", "PRIMARY4"),
                    ("JSS 1", "JSS 1"),
                    ("JSS 2", "JSS 2"),
                    ("JSS 3", "JSS 3"),
                    ("SSS 1", "SSS 1"),
                    ("SSS 2", "SSS 2"),
                    ("SSS 3", "SSS 3"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="state_of_origin",
            field=models.CharField(
                choices=[
                    ("ABIA", "Abia"),
                    ("ADAMAWA", "Adamawa"),
                    ("AKWA IBOM", "Akwa Ibom"),
                    ("ANAMBRA", "Anambra"),
                    ("BAUCHI", "Bauchi"),
                    ("BAYELSA", "Bayelsa"),
                    ("BENUE", "Benue"),
                    ("BORNO", "Borno"),
                    ("CROSS RIVER", "Cross River"),
                    ("DELTA", "Delta"),
                    ("EBONYI", "Ebonyi"),
                    ("EDO", "Edo"),
                    ("EKITI", "Ekiti"),
                    ("ENUGU", "Enugu"),
                    ("GOMBE", "Gombe"),
                    ("IMO", "Imo"),
                    ("JIGAWA", "Jigawa"),
                    ("KADUNA", "Kaduna"),
                    ("KANO", "Kano"),
                    ("KATSINA", "Katsina"),
                    ("KEBBI", "Kebbi"),
                    ("KOGI", "Kogi"),
                    ("KWARA", "Kwara"),
                    ("LAGOS", "Lagos"),
                    ("NASARAWA", "Nasarawa"),
                    ("NIGER", "Niger"),
                    ("OGUN", "Ogun"),
                    ("ONDO", "Ondo"),
                    ("OSUN", "Osun"),
                    ("OYON", "Oyo"),
                    ("PLATEAU", "Plateau"),
                    ("RIVERS", "Rivers"),
                    ("SOKOTO", "Sokoto"),
                    ("TARABA", "Taraba"),
                    ("YOBE", "Yobe"),
                    ("ZAMFARA", "Zamfara"),
                    ("FCT", "Federal Capital Territory"),
                ],
                max_length=100,
            ),
        ),
    ]
