# Generated by Django 5.1.1 on 2024-09-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0018_alter_application_class_applying"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="class_applying",
            field=models.CharField(
                choices=[
                    ("CREACH", "CREACH"),
                    ("KG 1", "KG 1"),
                    ("KG 2", "KG 2"),
                    ("NURSERY 1", "NURSERY 1"),
                    ("NURSERY 2", "NURSERY 3"),
                    ("NURSERY 3", "NURSERY 3"),
                    ("PRIMARY 1", "PRIMARY 1"),
                    ("PRIMARY 2", "PRIMARY 2"),
                    ("PRIMARY 2", "PRIMARY 2"),
                    ("PRIMARY 3", "PRIMARY 3"),
                    ("PRIMARY 4", "PRIMARY 4"),
                    ("PRIMARY 5", "PRIMARY 4"),
                    ("JSS 1", "JSS 1"),
                    ("JSS 2", "JSS 2"),
                    ("JSS 3", "JSS 3"),
                    ("SSS 1", "SSS 1"),
                    ("SSS 2", "SSS 2"),
                    ("SSS 3", "SSS 3"),
                ],
                max_length=10,
            ),
        ),
    ]
